<a href="https://colab.research.google.com/github/deepshikharbhardwaj/Natural_Language_Processing/blob/main/Custom_Dataset_TorchText.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mount Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd '/content/drive/MyDrive/PyTorch/Torchtext'

/content/drive/MyDrive/PyTorch/Torchtext


In [3]:
!pip install -U torchtext==0.8.0

     |████████████████████████████████| 7.0MB 7.8MB/s 
  Found existing installation: torchtext 0.9.1
    Uninstalling torchtext-0.9.1:
      Successfully uninstalled torchtext-0.9.1


In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
import spacy
from torchtext.data import Field, TabularDataset, BucketIterator

In [17]:
# STEPS:
# 1. Specify how preprocessing should be done -> Done by Fields
# 2. Use Dataset to load the data -> TabularDataset (JSON/CSV/TSV Files)
# 3. Construct an iterator to do batching & padding -> BucketIterator

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenize = lambda x: x.split()
# python -m spacy download en
#spacy_en = spacy.load("en")

#def tokenize(text):
#    return [tok.text for tok in spacy_en.tokenizer(text)]


quote = Field(sequential=True, use_vocab=True, tokenize=tokenize, lower=True) #PREPROCESSING
score = Field(sequential=False, use_vocab=False)

fields = {"quote": ("q", quote), "score": ("s", score)} #INPUT DATA Column -> quote and score -> categorize quote as (key q and value quote)

train_data, test_data = TabularDataset.splits(path="./", train="train.json", test="test.json", format="json", fields=fields)
print('\n',train_data[0].__dict__.keys(),'\n')
print('\n',train_data[0].__dict__.values(),'\n')

quote.build_vocab(train_data, max_size=10000, min_freq=1, vectors="glove.6B.100d") #min frequency -> consider that words which have atleast frequency of 1.
train_iterator, test_iterator = BucketIterator.splits((train_data, test_data), batch_size=1, device=device)

for batch in train_iterator:
  print('batch quote \n',batch.q)
  print('batch score \n', batch.s)





 # train_data, test_data = TabularDataset.splits(path='mydata', train='train.csv', test='test.csv', format='csv', fields=fields)                                    
 # train_data, test_data = TabularDataset.splits( path='mydata', train='train.tsv', test='test.tsv',format='tsv', fields=fields)

/usr/local/lib/python3.7/dist-packages/torchtext/data/field.py:150: UserWarning: Field class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/usr/local/lib/python3.7/dist-packages/torchtext/data/example.py:13: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)



 dict_keys(['q', 's']) 


 dict_values([['you', 'must', 'own', 'everything', 'in', 'your', 'world.', 'there', 'is', 'no', 'one', 'else', 'to', 'blame.'], 1]) 

batch quote 
 tensor([[10],
        [21],
        [ 4],
        [ 3],
        [ 6],
        [11],
        [17],
        [ 4],
        [ 3],
        [30],
        [28],
        [ 5],
        [13],
        [ 2],
        [ 9],
        [23]])
batch score 
 tensor([1])
batch quote 
 tensor([[33],
        [19],
        [24],
        [14],
        [15],
        [34],
        [32],
        [31],
        [16],
        [20],
        [22],
        [12],
        [ 5],
        [ 8]])
batch score 
 tensor([1])
batch quote 
 tensor([[27],
        [29],
        [ 7],
        [26],
        [18],
        [ 2],
        [25]])
batch score 
 tensor([0])


/usr/local/lib/python3.7/dist-packages/torchtext/data/iterator.py:48: UserWarning: BucketIterator class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/usr/local/lib/python3.7/dist-packages/torchtext/data/batch.py:23: UserWarning: Batch class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


#Using Spacy

In [18]:
# STEPS:
# 1. Specify how preprocessing should be done -> Done by Fields
# 2. Use Dataset to load the data -> TabularDataset (JSON/CSV/TSV Files)
# 3. Construct an iterator to do batching & padding -> BucketIterator

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#tokenize = lambda x: x.split()
# python -m spacy download en
spacy_en = spacy.load("en")

def tokenize(text):
    return [tok.text for tok in spacy_en.tokenizer(text)]


quote = Field(sequential=True, use_vocab=True, tokenize=tokenize, lower=True) #PREPROCESSING
score = Field(sequential=False, use_vocab=False)

fields = {"quote": ("q", quote), "score": ("s", score)} #INPUT DATA Column -> quote and score -> categorize quote as (key q and value quote)

train_data, test_data = TabularDataset.splits(path="./", train="train.json", test="test.json", format="json", fields=fields)
print('\n',train_data[0].__dict__.keys(),'\n')
print('\n',train_data[0].__dict__.values(),'\n')

quote.build_vocab(train_data, max_size=10000, min_freq=1, vectors="glove.6B.100d") #min frequency -> consider that words which have atleast frequency of 1.
train_iterator, test_iterator = BucketIterator.splits((train_data, test_data), batch_size=1, device=device)

for batch in train_iterator:
  print('batch quote \n',batch.q)
  print('batch score \n', batch.s)

/usr/local/lib/python3.7/dist-packages/torchtext/data/field.py:150: UserWarning: Field class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/usr/local/lib/python3.7/dist-packages/torchtext/data/example.py:13: UserWarning: Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('Example class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.', UserWarning)



 dict_keys(['q', 's']) 


 dict_values([['you', 'must', 'own', 'everything', 'in', 'your', 'world', '.', 'there', 'is', 'no', 'one', 'else', 'to', 'blame', '.'], 1]) 

batch quote 
 tensor([[14],
        [25],
        [ 7],
        [ 5],
        [10],
        [15],
        [21],
        [ 3],
        [ 7],
        [ 5],
        [32],
        [30],
        [ 8],
        [17],
        [ 4],
        [13],
        [ 6],
        [ 2]])
batch score 
 tensor([1])
batch quote 
 tensor([[35],
        [23],
        [26],
        [18],
        [19],
        [36],
        [34],
        [ 2],
        [33],
        [20],
        [24],
        [ 6],
        [16],
        [ 8],
        [12],
        [ 2]])
batch score 
 tensor([1])
batch quote 
 tensor([[29],
        [31],
        [ 3],
        [11],
        [28],
        [22],
        [ 4],
        [27],
        [ 9]])
batch score 
 tensor([0])


/usr/local/lib/python3.7/dist-packages/torchtext/data/iterator.py:48: UserWarning: BucketIterator class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
/usr/local/lib/python3.7/dist-packages/torchtext/data/batch.py:23: UserWarning: Batch class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


#Create RNN

In [19]:
######### Training a simple LSTM on this toy data of ours #########
class RNN_LSTM(nn.Module):
    def __init__(self, input_size, embed_size, hidden_size, num_layers):
        super(RNN_LSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(input_size, embed_size)
        self.rnn = nn.LSTM(embed_size, hidden_size, num_layers)
        self.fc_out = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # Set initial hidden and cell states
        h0 = torch.zeros(self.num_layers, x.size(1), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(1), self.hidden_size).to(device)

        embedded = self.embedding(x)
        outputs, _ = self.rnn(embedded, (h0, c0))
        prediction = self.fc_out(outputs[-1, :, :])

        return prediction


#Hyperparameters

In [20]:
input_size = len(quote.vocab)
hidden_size = 512
num_layers = 2
embedding_size = 100
learning_rate = 0.005
num_epochs = 10

#Initialize Network

In [21]:
model = RNN_LSTM(input_size, embedding_size, hidden_size, num_layers).to(device)

#Load the pretrained embeddings onto our model

In [22]:
pretrained_embeddings = quote.vocab.vectors
model.embedding.weight.data.copy_(pretrained_embeddings)

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.3398,  0.2094,  0.4635,  ..., -0.2339,  0.4730, -0.0288],
        ...,
        [ 0.4918,  1.1164,  1.1424,  ..., -0.5088,  0.6256,  0.4392],
        [-0.4989,  0.7660,  0.8975,  ..., -0.4118,  0.4054,  0.7850],
        [-0.5718,  0.0463,  0.8673,  ..., -0.3566,  0.9293,  0.8995]])

#Loss and Optimizer

In [23]:
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

#Train Network

In [24]:
for epoch in range(num_epochs):
    losses=[]
    for batch_idx, batch in enumerate(train_iterator):
        # Get data to cuda if possible
        data = batch.q.to(device=device)
        targets = batch.s.to(device=device)

        # forward
        scores = model(data)
        #print(scores.shape)
        loss = criterion(scores.squeeze(1), targets.type_as(scores))
        losses.append(loss.item())

        # backward
        optimizer.zero_grad()
        loss.backward()

        # gradient descent
        optimizer.step()
    print(f"Loss at epoch {epoch} is { sum(losses)/len(losses) :.5f}")

/usr/local/lib/python3.7/dist-packages/torchtext/data/batch.py:23: UserWarning: Batch class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)


Loss at epoch 0 is 1.49979
Loss at epoch 1 is 1.18254
Loss at epoch 2 is 0.85307
Loss at epoch 3 is 0.67532
Loss at epoch 4 is 0.70580
Loss at epoch 5 is 0.69835
Loss at epoch 6 is 0.64906
Loss at epoch 7 is 0.64026
Loss at epoch 8 is 0.64026
Loss at epoch 9 is 0.63241


#Accuracy

In [25]:
def check_accuracy(loader,model):
  if loader.dataset.train:
        print('Checking Accuracy on Training Data')
  else:
        print('Checking Accuracy on Test Data')
  num_correct=0
  num_samples=0
  model.eval()

  for batch_idx, batch in enumerate(train_iterator):
      x = batch.q.to(device=device)
      y = batch.s.to(device=device)
      scores=model(x)  
      values,predictions =scores.max(1)  #interested in index of the max value
      num_correct += (predictions==y).sum()
      num_samples += predictions.size(0) 

  print(f'Got {num_correct}/ {num_samples} with accuracy {float(num_correct)/float(num_samples)*100:.2f} \n')

  model.train()

check_accuracy(train_iterator, model)
check_accuracy(test_iterator, model)

Checking Accuracy on Training Data
Got 1/ 3 with accuracy 33.33 

Checking Accuracy on Training Data
Got 1/ 3 with accuracy 33.33 



/usr/local/lib/python3.7/dist-packages/torchtext/data/batch.py:23: UserWarning: Batch class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.
  warnings.warn('{} class will be retired soon and moved to torchtext.legacy. Please see the most recent release notes for further information.'.format(self.__class__.__name__), UserWarning)
